# Use postgres/example user/password credentials
version: '3.7'
services:
  db:
    container_name: oms_postgres_docker
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - local_docker
  pgadmin:
    container_name: oms_pgadmin_docker
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}"
    depends_on:
      - db
    networks:
      - local_docker
  redis:
    container_name: oms_redis_docker
    image: redis:latest
    restart: always
    ports:
      - "${MEMORY_CACHE_PORT}:6379"
    networks:
      - local_docker
networks:
  local_docker: