version: '3.1'
services:
  ################################
  #   Setup CACHE container
  ################################
  dev_cache:
    build:
      context: ${REPO_CACHE}
      dockerfile: Dockerfile
      args:
        - CACHE_REMOTE_PORT=${CACHE_REMOTE_PORT}
    ports:
      - ${CACHE_EXTERNAL_PORT_DEV}:${CACHE_REMOTE_PORT}
    container_name: dev_cache_fastify
    networks:
      - web
  ################################
  #   Setup DB container
  ################################
  dev_db:
    build:
      context: ${REPO_DATABASE}
      dockerfile: Dockerfile
      args:
        - DB_REMOTE_PORT=${DB_REMOTE_PORT}
    ports:
      - ${DB_EXTERNAL_PORT_DEV}:${DB_REMOTE_PORT}
    environment:
      ################################
      #   DB LITE CONFIG
      ################################
      - POSTGRES_USER=${DB_REMOTE_GLOBAL_USER}
      - POSTGRES_PASSWORD=${DB_REMOTE_GLOBAL_PASS}
      - POSTGRES_DB=${DB_REMOTE_DB_DEV}
    container_name: dev_database_fastify
    networks:
      - web
  ################################
  #   Setup DB ADMIN container
  ################################
  dev_db_admin:
    build:
      context: ${REPO_DATABASE_ADMIN}
      dockerfile: Dockerfile
      args:
        - DB_REMOTE_PORT=${DB_ADMIN_REMOTE_PORT}
    logging:
      driver: none
    ports:
      - ${DB_ADMIN_EXTERNAL_PORT_DEV}:${DB_ADMIN_REMOTE_PORT}
    environment:
      ################################
      #   DB ADMIN LITE CONFIG
      ################################
      - PGADMIN_DEFAULT_EMAIL=${DB_ADMIN_GLOBAL_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_ADMIN_GLOBAL_PASS}
    container_name: dev_database_admin_fastify
    networks:
      - web
networks:
  web: